# Generated by Django 4.0 on 2022-11-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameContact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=320)),
                ('phone', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=600)),
            ],
        ),
    ]
