# Generated by Django 4.0 on 2022-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petwatcher',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
