# Generated by Django 4.0 on 2022-12-01 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_hotel', '0004_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pet_hotel.customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pet_hotel.pet'),
        ),
    ]
