# Generated by Django 4.0 on 2022-12-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_hotel', '0006_remove_appointment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_hotel.pet'),
        ),
    ]
