# Generated by Django 4.0 on 2022-12-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_hotel', '0007_alter_appointment_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, default=1964, on_delete=django.db.models.deletion.CASCADE, to='pet_hotel.customer'),
            preserve_default=False,
        ),
    ]
