# Generated by Django 4.0 on 2022-12-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_hotel', '0008_appointment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, default='Pendiente', max_length=200),
        ),
    ]
